import { EB_Garamond, Fira_Mono, Lato, Montserrat } from "next/font/google"
import "@/styles/globals.css"
import Navbar from "@/components/Navbar"

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
})

const garamond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-garamond",
})

const firaMono = Fira_Mono({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-firaMono",
})

const lato = Lato({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-lato",
})

export const metadata = {
  title: "Livenberg",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${lato.variable} ${montserrat.variable} ${firaMono.variable}  ${garamond.variable}`}
    >
      <body className="dark min-h-screen">
        <div className="relative flex min-h-screen flex-col">
          <header className="sticky top-0 border-b border-solid border-b-border shadow-sm">
            <Navbar />
          </header>
          <main className="flex flex-1 flex-col font-lato">{children}</main>
        </div>
      </body>
    </html>
  )
}
